import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="container mx-auto flex justify-between px-10 py-10 ">
          <a href="/" className='text-4xl font-bold'>Logo</a>
          <nav className="space-x-5">
            <Link className='nav-btn text-2xl' href="/users">Users</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
